import { useBox } from "@react-three/cannon";
import { Html, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export default function Flag({ position, wallColor, nextRound }) {
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/flag/model.gltf"
  );

  const [ref] = useBox(() => ({
    mass: 0,
    args: [0.6, 2, 0.6],
    position: [position.x, 0.5, position.z],
    onCollide: (e) => nextRound(),
  }));
  return (
    <group ref={ref} position={[position.x, -0.5, position.z]}>
      <group position={[0, -1, 0]} rotation={[Math.PI / 2, 0, Math.PI * 2 * Math.random()]}>
        <mesh
          geometry={nodes.Cube1351.geometry}
          material={materials["Blue.011"]}
          material-color={wallColor}
        />
        <mesh geometry={nodes.Cube1351_1.geometry} material={materials["Brown.006"]} />
        <mesh geometry={nodes.Cube1351_2.geometry} material={materials["Metal.019"]} />
      </group>
    </group>
  );
}
useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/flag/model.gltf"
);
